name: GitHub Pages CI

on:
  workflow_run:
    workflows: ["ESP32 Arduino Release"]
    types:
      - completed
  push:
    branches:
      - master
      - main
      - pages
    paths:
      - "README.md"
      - ".github/scripts/on-pages.sh"
      - ".github/workflows/gh-pages.yml"

permissions:
  contents: write
  pages: write

jobs:
  build-pages:
    name: Build GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Copy Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./.github/scripts/on-pages.sh
