name: ESP32 Arduino Release

on:
  release:
    types: published

permissions:
  contents: write
  pages: write

jobs:
  build:
    name: Build Release Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.0.4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install packaging pyserial

      - name: Build Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./.github/scripts/on-release.sh

      - name: Upload build JSONs for testing
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-output
          path: ${{ github.workspace }}/build
          if-no-files-found: error

  test-package:
    name: Test Package
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.0.4
        with:
          python-version: "3.x"

      - name: Install pyserial
        run: pip install pyserial

      - name: Download build artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: build-output
          path: ${{ github.workspace }}/build

      - name: Test package installation
        env:
          RELEASE_PRE: ${{ github.event.release.prerelease }}
        run: bash ./.github/scripts/test-package-json.sh

  upload-and-finalize:
    name: Upload Package JSONs and Finalize Release
    needs: [build, test-package]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: build-output
          path: ${{ github.workspace }}/build

      - name: Upload package JSONs to release and GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_PRE: ${{ github.event.release.prerelease }}
          RELEASE_ID: ${{ github.event.release.id }}
        run: bash ./.github/scripts/upload-release-assets.sh
